name: AgroLens
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  otp_text_field: ^1.1.3
  otp_autofill: ^4.1.0
  # pinput: ^5.0.1
  smart_auth: ^3.2.0
  flutter_animate: ^4.5.2
  page_transition: ^2.1.0
  flutter_bloc: ^9.1.0
  camera: ^0.11.0
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  http: ^1.3.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  share_plus: ^10.1.4
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1
  google_nav_bar: ^5.0.7
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  transparent_image: ^2.0.1
  translator: ^1.0.3
  shared_preferences: ^2.3.3
  animated_bottom_navigation_bar: ^1.4.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/PlantAir.png
    - assets/.env
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
